database:
  driverClass: org.postgresql.Driver
  user: voldemort
  password: hewhomustnotbenamed
  url: jdbc:postgresql:assignment_6

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  
  maxWaitForConnection: 1s
  validationQuery: "/* Postgres Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  rootPath: /

logging:
  level: INFO
  loggers:
    brendan.csc435: DEBUG